server:
  port: 8788
  
spring:
  application:
    name: warehouseenter

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

security:
  oauth2:
    resource:
      jwt:
        key-value: test-secret
        
testkey: aqqqqqqqq
















