server:
  port: 8764
  
spring:
  application:
    name: warehouseenter

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:abc123@localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

security:
  oauth2:
    resource:
      jwt:
        key-value: test-secret
















